import { MEDIA_ORIGIN, SITE_URL } from './site';

/**
 * The games the selector enumerates — the single source of truth for the
 * selector cards, the ItemList JSON-LD, and the sitemap index. Dependency-free
 * (no Nuxt/Vue imports) so it's importable from BOTH app code (the selector
 * page, via app.config.ts) and the build-time sitemap-index module (jiti).
 *
 * Per PLAN §5 prompt A.2, each game carries { id, name, shortName, slug, url,
 * accent, art }. `accent` + `art` are the ONLY per-game color on the umbrella
 * selector (the page chrome itself stays neutral/umbrella); `url` is the apex
 * subpath the shell rewrites to its deployment.
 */
export interface ShellGame {
  /** GameConfig.id — stable identity, also the JSON-LD item id fragment. */
  id: string;
  /** Full title, e.g. 'Tekken 8'. The card heading + JSON-LD name. */
  name: string;
  /** Brand wordmark short form, e.g. 'TEKKEN' / '2XKO'. */
  shortName: string;
  /** URL segment / base path segment (no slashes), e.g. 'tekken'. */
  slug: string;
  /** Apex path the card links to (edge-rewritten to the game deployment). */
  url: string;
  /** The game's own accent hex — the card's only chromatic departure from the
   *  umbrella theme (matches the game's theme.css --color-primary). */
  accent: string;
  /** Bundled key art (public path). The game's own og-default lockup — a
   *  byte-copy of `<game-repo>/public/og-default.png`.
   *
   *  IT CONTAINS ITS OWN COPY LINE, generated by that repo's `scripts/og.ts`
   *  (`KICKER` in SF6's, `L2` in CotW's, `TAGLINE` in Granblue's, inline in
   *  2XKO's and Tekken's), and those still read "character usage · … · meta
   *  over time" — the sentence
   *  `tagline` below was rewritten to stop repeating. The art and the card
   *  therefore disagree today. It is a 20px line inside a 1200px image, so it
   *  renders at ~5px on a card and is effectively illegible, which is why this
   *  was accepted rather than fixed: fixing it means editing seven game repos,
   *  regenerating each og-default.png, and re-copying it here — and it changes
   *  every game's social preview as a side effect. If you ever regenerate one,
   *  regenerate all seven, and match the new taglines while you are there. */
  art: string;
  /** Self-hosted muted hover-loop (public path), trimmed from the game's own
   *  hero video. Plays over `art` while the selector card is hovered/focused.
   *  OPTIONAL: a game without one simply shows its static key art. */
  video?: string;
  /** The card's blurb: what THIS archive holds that its neighbours' do not.
   *
   *  It used to read "the feature triplet from the game's key art", and copying
   *  the art is exactly how four of five cards ended up as variations on
   *  "Character usage · <something> · meta over time" — a line that describes
   *  every archive here and therefore none of them. Name the thing only this
   *  game's data has: 2XKO's Fuse facet, Tekken's ladder, Tōkon's four-fighter
   *  sides, CotW's patch depth. verify-shell gates distinctness, so a fifth
   *  variation now fails the build rather than shipping.
   *
   *  NEVER A NUMBER THAT GROWS — no roster size, no patch count, no replay
   *  total. Rosters gain DLC and patch trees gain seasons, and this file is
   *  baked into static HTML that only redeploys when the SHELL changes, so a
   *  count here goes stale while nobody is looking. The live number the card
   *  does show comes from the game's own summary.json at runtime.
   *
   *  Wraps to at most TWO lines and never truncates (`.tagline` in index.vue
   *  reserves both). The budget is the narrowest card, which is the sm 2-up at
   *  640 and not the 3-up: ~36 characters a line, so ≤60 characters total. */
  tagline: string;
  /** Absolute /<slug>/sitemap.xml on the apex — referenced by the index. */
  sitemapUrl: string;
  /** Count source for the selector card (PLAN §5 A.4 / Phase 6). SUBPATH-
   *  RELATIVE on purpose: the selector fetches it client-side, so it must go
   *  through the shell's own rewrite (vercel.json) and stay SAME-ORIGIN — an
   *  absolute game-host URL would be cross-origin from the apex and the browser
   *  would block it (the games send no CORS headers). Emitted by each game's
   *  pipeline; a game that hasn't shipped it yet 404s and its count is simply
   *  omitted (never faked, and never derived from the 1 MB replays.json). */
  summaryUrl: string;
}

export const GAMES: ShellGame[] = [
  {
    id: '2xko',
    name: '2XKO',
    shortName: '2XKO',
    slug: '2xko',
    url: '/2xko',
    accent: '#ff2e88',
    art: '/img/games/2xko.png',
    video: `${MEDIA_ORIGIN}/video/games/2xko.mp4`,
    tagline: 'Champion duos, and the Fuse each team ran',
    sitemapUrl: `${SITE_URL}/2xko/sitemap.xml`,
    summaryUrl: '/2xko/data/summary.json',
  },
  {
    id: 'tekken8',
    name: 'Tekken 8',
    shortName: 'TEKKEN',
    slug: 'tekken',
    url: '/tekken',
    accent: '#e13048',
    art: '/img/games/tekken.png',
    video: `${MEDIA_ORIGIN}/video/games/tekken.mp4`,
    tagline: 'Ranked play, up to God of Destruction',
    sitemapUrl: `${SITE_URL}/tekken/sitemap.xml`,
    summaryUrl: '/tekken/data/summary.json',
  },
  {
    // APPEND, don't insert: verify-shell asserts the ItemList JSON-LD
    // positionally, so reordering GAMES silently breaks the gate.
    id: 'sf6',
    name: 'Street Fighter 6',
    shortName: 'SF6',
    slug: 'sf6',
    url: '/sf6',
    // matches the game's theme.css --color-primary; lowercase because the
    // gates compare against lowercased computed values
    accent: '#ff7d00',
    art: '/img/games/sf6.png',
    video: `${MEDIA_ORIGIN}/video/games/sf6.mp4`,
    tagline: 'Any matchup, from either side of it',
    sitemapUrl: `${SITE_URL}/sf6/sitemap.xml`,
    summaryUrl: '/sf6/data/summary.json',
  },
  {
    // Promoted out of UPCOMING on 2026-08-14. Appended, per the note above.
    id: 'tokon',
    // The short form the game is actually called, parallel to 'Tekken 8' and
    // '2XKO'. The full title "MARVEL Tōkon: Fighting Souls" wraps to two lines
    // in the title column, and a wrapped title sits at a different height from
    // its row-mate's, so it lives in the card art and the image alt instead.
    // The measurement behind this MOVED when the "Browse →" CTA left the title's
    // line box: the column is the full card now, 241px at the narrowest regime
    // (the sm 2-up at 640) and 334px at the 3-up, not the 164px it was. The
    // short names all clear that comfortably — verify-shell asserts one line per
    // title at every regime — but the full ones still do not, which is why this
    // field exists.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'MARVEL Tōkon',
    shortName: 'TŌKON',
    slug: 'tokon',
    url: '/tokon',
    // The game's theme.css --color-primary, per the contract above. The
    // coming-soon card carried #00a6ff, sampled from the Marvel CDN wordmark;
    // the shipped skin resolved SOULS blue slightly differently, and it is the
    // computed value that verify-cutover compares through the proxy — so the
    // card follows the game, not the other way round.
    accent: '#03a5fe',
    art: '/img/games/tokon.png',
    video: `${MEDIA_ORIGIN}/video/games/tokon.mp4`,
    tagline: 'Four-fighter teams on a shared life bar',
    sitemapUrl: `${SITE_URL}/tokon/sitemap.xml`,
    summaryUrl: '/tokon/data/summary.json',
  },
  {
    // Game #5, appended per the note above. It never passed through UPCOMING:
    // that array has been empty since Tōkon shipped, so this is a plain append
    // rather than a promotion, and there is no coming-soon card to retire.
    id: 'ffcotw',
    // The short form the game is actually called. The full title
    // "FATAL FURY: City of the Wolves" is longer than any sibling's and wraps
    // in the card's title column; it lives in the card art and the image alt
    // instead, exactly as MARVEL Tōkon's does.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'FATAL FURY: CotW',
    shortName: 'COTW',
    slug: 'ffcotw',
    url: '/ffcotw',
    // The game's theme.css --color-primary. Yellow rather than the sampled
    // FATAL FURY red, by the skin's own collision lever: that red is 11° of hue
    // from Tekken's #e13048 and would be indistinguishable from it at chip size.
    accent: '#ffd21f',
    // A byte-copy of the game repo's own public/og-default.png, which is how
    // 2XKO, Tekken and SF6's cards were made. Tōkon needed a bespoke generator
    // only because it had no game repo at the time; this one does.
    art: '/img/games/ffcotw.png',
    // 1:44–1:55 of the Official Special Anime Trailer, trimmed to the siblings'
    // shape: 1280×720, 30fps, muted (no audio stream at all), 11s.
    video: `${MEDIA_ORIGIN}/video/games/ffcotw.mp4`,
    tagline: 'Every patch since the open beta',
    sitemapUrl: `${SITE_URL}/ffcotw/sitemap.xml`,
    summaryUrl: '/ffcotw/data/summary.json',
  },
  {
    // Game #6, appended per the note above — and the first PROMOTION out of
    // UPCOMING since Tōkon's. Its coming-soon card is retired in this same
    // commit, which is what the `art` swap below is really about: the announced
    // art says "Coming soon to the Replay Database" in 40px type, so leaving it
    // would ship a live, clickable card advertising itself as unavailable.
    id: 'ggst',
    // The short form, parallel to 'MARVEL Tōkon' and 'FATAL FURY: CotW'. The
    // official title is GUILTY GEAR -STRIVE-, and its hyphen-flanked wordmark
    // both wraps in the title column and reads as a stray dash where it breaks.
    // The full spelling survives in the card art, which sets it in the lockup.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'Guilty Gear Strive',
    shortName: 'STRIVE',
    slug: 'ggst',
    url: '/ggst',
    // The game's theme.css --color-primary. UNCHANGED from the coming-soon
    // card's provisional value, which is worth saying out loud because the rule
    // is that the theme wins at flip time and Tōkon's card really did move
    // (#00a6ff → #03a5fe): this skin resolved the gold-foil capsule to the same
    // hex the handoff had anchored, so there was nothing to follow. Its two
    // tight neighbours are unchanged with it — CotW's #ffd21f at Δhue 11 with
    // ΔL .125 against a .12 floor, and the engine's umbrella --color-secondary
    // #fbc318 at Δhue 5 with ΔL .00, separated on chroma alone. Anyone
    // re-sampling this gold has to clear BOTH, not just the live accents.
    accent: '#d9a53a',
    // A byte-copy of the game repo's own public/og-default.png, the way 2XKO,
    // Tekken, SF6 and CotW's were made. This one carries "Character art
    // © ARC SYSTEM WORKS" baked into the image — the Fan Kit licence's
    // Article 3.1 attribution travelling with the art onto the front door. It
    // is the only card art here with a licence obligation attached, so it may
    // be re-exported from that repo but never cropped past the notice.
    // It inherits the copy-line disagreement described on `art` above: the
    // lockup reads "Character usage · matchups · meta over time" while the
    // tagline says something else entirely. Accepted on the same terms as the
    // other five — ~5px on a rendered card — not overlooked.
    art: '/img/games/ggst.png',
    // 1:29-1:46 of the official "Find Your One Way" 1st Anniversary MV,
    // trimmed to the siblings' shape: 1280×720, 30fps, muted (no audio
    // stream at all), 17s.
    video: `${MEDIA_ORIGIN}/video/games/ggst.mp4`,
    // The archive's own shape is the line worth having here, and no sibling can
    // claim it: the eight channels upload whole SETS (every one's median run
    // is over three and a half minutes, against a ~3-minute Strive game), while
    // the Replay Theater catalogue contributes single matches cut out of
    // tournament VODs at an offset. Not a count, and it cannot go stale.
    tagline: 'Whole sets, and matches cut from tournament streams',
    sitemapUrl: `${SITE_URL}/ggst/sitemap.xml`,
    summaryUrl: '/ggst/data/summary.json',
  },
  {
    // Game #7, appended per the note above — the second PROMOTION out of
    // UPCOMING since Tōkon's (Strive's was the first). Its coming-soon card is
    // retired in this same commit: the announced art says "Coming soon to the
    // Replay Database" in 40px type, so leaving it would ship a live, clickable
    // card advertising itself as unavailable. Its register in
    // scripts/card-art-upcoming.mjs is deleted in this commit for the same
    // reason — that script's bare default run renders EVERY register, and a
    // register for a live game is a command that overwrites live art with a
    // Coming Soon tile.
    id: 'gbvsr',
    // The short form the coming-soon card already carried, parallel to 'MARVEL
    // Tōkon' and 'FATAL FURY: CotW', so the heading does not move at promotion.
    // The official title "Granblue Fantasy Versus: Rising" wraps in the title
    // column at every regime and lives in the card art instead.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'Granblue Rising',
    shortName: 'GBVSR',
    slug: 'gbvsr',
    url: '/gbvsr',
    // The game's theme.css --color-primary, lowercased. THE CARD FOLLOWED THE
    // GAME: the coming-soon card carried a provisional #5569ff (the key-visual
    // logo's ultramarine, lifted for AA and pushed 8° of hue away from Tōkon),
    // and the shipped skin took the logo's sky blue #4da6ff instead.
    //
    // THIS IS THE CLOSEST PAIR ON THE DOOR, and it ships on the 2026-09-15
    // colour policy rather than by oversight. Measured in OKLCH against Tōkon's
    // #03a5fe: Δhue 7.0, ΔL .016 — under both floors of the advisory rule below,
    // and tighter than any collision accepted before it. The policy is what
    // permits it: a game with a clear colour identity uses it, and the grid and
    // the changelog badges carry wordmarks, art and text labels that do the
    // identifying. The note on the provisional value predicted exactly this
    // ("the logo's sky #5bc9fa … blocked outright: Δhue 14 from Tōkon") and the
    // skin chose its identity anyway. Every other live accent clears it widely
    // (Δhue ≥ 60 from the umbrella teal, ≥ 110 from the five warm ones).
    accent: '#4da6ff',
    // A byte-copy of the game repo's own public/og-default.png (1200×630,
    // 276,134 bytes, verified with cmp), the way every sibling's was made. IT
    // CARRIES NO KIT ART — the card is type, colour and a 40-segment roster
    // stripe — but it does carry "Character art © Cygames, Inc. · 2B © SQUARE
    // ENIX" baked in, because the game's pages show Fan Kit art and the notice
    // travels with the brand (that repo's scripts/og.ts). Reused here like the
    // other six on that reading: the clause that keeps the game's support link
    // on its own pages covers the front door too.
    // It inherits the copy-line disagreement described on `art` above: the
    // lockup reads "Character usage · matchups · meta over time" while the
    // tagline says something else. Accepted on the same terms as the others.
    art: '/img/games/gbvsr.png',
    // 0:13-0:31 of "Granblue Fantasy Versus: Rising - EVO Japan 2023 Trailer"
    // (youtube.com/watch?v=Q4928u3tddI, Cygames EN, the rights holder's own
    // channel): an in-engine showcase — Gran, Percival, Ferry, Vaseraga and
    // more — cut from the 1080p60 H.264 source to the siblings' shape: 1280×720,
    // 30fps, H.264 High, yuv420p, no audio stream, faststart, 18.0s, 4.68 MB
    // (capped at 2.0 Mb/s, about Strive's average; 0 black frames). The
    // trailer's own "GBVS RISING" logo bug sits top-left throughout.
    // A DELIBERATE EXCEPTION TO THIS GAME'S LICENCE FINDING, as Avatar's loop
    // is to its own. The game's art comes ONLY from Cygames' Fan Kit, whose
    // Article 1 says "Other copyrighted materials relating to the Content may
    // not be posted to or reprinted on external websites" — which a re-hosted
    // trailer clip is. The owner chose this clip on 2026-10-01 with that
    // conflict put to them first. And it falls OUTSIDE the game repo's
    // revocation command: `npm run data:art:revoked` there cannot reach this
    // shell's Blob store, so a revocation (Article 3) must also delete this
    // line and the blob — that repo's art.ts prints the step.
    video: `${MEDIA_ORIGIN}/video/games/gbvsr.mp4`,
    // The EX mark is the line only this archive can claim: Ver 2.20 gave three
    // fighters an EX mode, and a record carries the mark when — and only when —
    // its source said so. "Sets" because every intake uploads whole sets, never
    // single games. Not a count, and it cannot go stale.
    tagline: 'One-on-one sets, with EX mode wherever it is marked',
    sitemapUrl: `${SITE_URL}/gbvsr/sitemap.xml`,
    summaryUrl: '/gbvsr/data/summary.json',
  },
];

/**
 * Games ANNOUNCED but not yet in the archive — the selector's coming-soon cards
 * and nothing else.
 *
 * Deliberately a SEPARATE array with its own narrower type rather than a
 * `status` field on ShellGame. GAMES feeds three surfaces — the cards, the
 * ItemList JSON-LD, and the sitemap index — and only the first of those may show
 * a game that has no replays: an upcoming game in structured data or a sitemap is
 * a lie to crawlers. A `status` flag would push that correctness burden onto
 * every consumer forever, and two of the three fail SILENTLY when someone
 * forgets. This type has no `url`, no `sitemapUrl` and no `summaryUrl` at all, so
 * `modules/sitemap-index.ts` and the JSON-LD literally cannot reach it, even by
 * mistake. Only the card grid reads UPCOMING.
 *
 * Promoting one when its pipeline ships: move the entry into GAMES (appending,
 * per the note there), fill in the URL fields, and add the vercel.json rewrite
 * pair + the insights rewrite in the same commit — see README "Adding a game to
 * the selector".
 */
export interface UpcomingGame {
  /** Stable identity — the v-for key, and the future GameConfig.id. */
  id: string;
  /** The SHORT display form — the card's title column and nothing else. NOT the
   *  full title: spelled out, every one of these wraps, and a wrapped title sits
   *  at a different height from its row-mate's. The column is the full card
   *  width since the CTA moved onto the count row — 241px at the narrowest
   *  regime (sm 2-up at 640), 334px at the 3-up — and the full titles still
   *  exceed it. Parallel to the live cards' 'Tekken 8' / 'MARVEL Tōkon' /
   *  'FATAL FURY: CotW'. verify-shell gates one line per title at every
   *  regime. */
  name: string;
  /** The full title as the rights holder writes it, diacritics included. The
   *  card title cannot carry it (see `name`), so the image ALT and the card art
   *  do. A hard-coded literal here is what shipped the Tōkon alt onto every
   *  card that followed; index.vue binds this instead. */
  fullName: string;
  /** Brand wordmark short form. Official casing/diacritics render verbatim,
   *  same principle as Tekken's deliberate 'TEKKEN'. */
  shortName: string;
  /** The slug this game WILL own once it ships. ASCII — the macron is display
   *  only and never reaches a URL. */
  slug: string;
  /** Accent hex, lowercase (the gates compare against lowercased computed
   *  values). Drives the accent bar and the Coming Soon badge. */
  accent: string;
  /** Bundled card art (public path), 1200×630 to match the live cards. */
  art: string;
  /** Blurb describing the GAME, not an archive — there is no archive yet, and
   *  claiming one would be the same lie this type's missing url/summaryUrl
   *  fields exist to prevent. Same shape as ShellGame.tagline otherwise: two
   *  lines, ≤60 characters, distinct from every sibling (gated).
   *  NEVER A DATE — see below. */
  tagline: string;
}

// Empty from 2026-08-14 (MARVEL Tōkon's promotion into GAMES) until three games
// were announced; two once Guilty Gear Strive was promoted on 2026-09-09, and
// ONE since Granblue Rising was promoted on 2026-10-01. The narrow type above is
// what kept that window honest, and it is what keeps the last one out of the
// sitemap index and the ItemList now.
//
// PROMOTING ONE IS A SUBTRACTION HERE AND AN APPEND THERE, in the same commit.
// Neither Strive's entry nor Granblue's moved between the arrays: UpcomingGame and ShellGame
// share only five of their fields, so `fullName` was DROPPED (ShellGame has no
// such field) and `url`, `sitemapUrl` and `summaryUrl` were added. The full
// title therefore leaves the DOM at promotion — it lives in the card art and
// nowhere else, exactly as MARVEL Tōkon's and FATAL FURY's do.
//
// ORDER IS DISPLAY ORDER. Unlike GAMES — where APPEND-don't-insert protects a
// POSITIONAL JSON-LD gate — this array reaches only the card grid, which renders
// it in sequence. verify-shell asserts the cards positionally too, so reordering
// here is a deliberate act with a failing gate attached, not a silent one. AT
// ONE ENTRY THAT ASSERTION PROVES NOTHING ABOUT ORDER — a one-element array is
// in order by construction — and the next announcement restores it.
//
// ACCENTS ARE PROVISIONAL, and say so per entry. Each is the modal exact fill of
// an official asset (the sampling method is in scripts/card-art-upcoming.mjs),
// lifted where the sampled value is too dark to carry the badge's 11px text.
// At flip time THE THEME WINS: Tōkon's card carried #00a6ff and the shipped skin
// resolved to #03a5fe, and the card followed the game rather than the reverse.
//
// The separation rule every one of them clears, against all SIX live accents
// (Strive's gold joined that set when it was promoted), the umbrella teal, and
// each other: OKLCH Δhue ≥ 25, or Δhue ≥ 10 with |ΔL| ≥ .12. It is the rule the
// game skins already use, and it is why FATAL FURY demoted its own sampled red
// (11° from Tekken) to secondary.
export const UPCOMING: UpcomingGame[] = [
  {
    id: 'avatar',
    // Avatar Legends: The Fighting Game. The studio credits are the one fact
    // here that no single official surface settles, so the disagreement is
    // recorded rather than smoothed over:
    //   · Steam app 2424420 (publisher-submitted fields) — developer
    //     "Gameplay Group International", publishers "PM Studios, Inc." and
    //     "Paramount Games"
    //   · nintendo.com product page — publisher "PM Studios", no developer
    //   · paramountgames.com/games/avatar-legends-the-fighting-game — credits
    //     "Paramount Games Studio" as both
    // Resolved by the maintainer's own confirmation: developer Gameplay Group
    // International, publisher PM Studios, Inc. The tagline carries the
    // rights-holder × developer pair; "Paramount" is the rights holder, as
    // "Marvel" was on Tōkon's card before that one moved to describing its
    // archive. This is the only card left in the ×-credit shape, which is why
    // it is the one that kept its line unchanged.
    // Slug is 'avatar', not ComboForge's 'ava': this becomes a permanent public
    // path and readability wins there; the CF id stays a config map.
    name: 'Avatar Legends',
    fullName: 'Avatar Legends: The Fighting Game',
    shortName: 'AVATAR',
    slug: 'avatar',
    // PROVISIONAL. Sampled from the official site's own logo
    // (avatarfighters.com): a dusk indigo #363c88, 54.3% of that asset's flat
    // fills. Lifted L .395 → .778 for AA — the sampled value is 2.06:1 on the
    // card ground and the badge sets 11px text in it.
    // WORTH KNOWING before re-sampling: the logo at
    // paramountgames.com/avatar-assets/brand/avatar-logo-clean.png and all four
    // element seals under /avatar-assets/brand/seals/ are pure WHITE line art
    // on transparent — zero chroma, no accent to take. The key art is a painted
    // composition whose dominant fills are a cream wash and a fire red 11° from
    // Tekken. The indigo is the only viable band the official art offers.
    // Δhue 36 from Tōkon, 90 from the umbrella teal. It was separated from
    // Granblue's provisional #5569ff by lightness while both were announced;
    // that card is live now as #4da6ff, Δhue 33.5 from this one.
    accent: '#aeacff',
    art: '/img/games/avatar.png',
    tagline: 'Four elements · Paramount × Gameplay Group',
  },
];
