import { SITE_URL } from './site';

/**
 * The games the selector enumerates — the single source of truth for the
 * selector cards, the ItemList JSON-LD, and the sitemap index. Dependency-free
 * (no Nuxt/Vue imports) so it's importable from BOTH app code (the selector
 * page, via app.config.ts) and the build-time sitemap-index module (jiti).
 *
 * Per PLAN §5 prompt A.2, each game carries { id, name, shortName, slug, url,
 * accent, art }. `accent` + `art` are the ONLY per-game color on the umbrella
 * selector (the page chrome itself stays neutral/umbrella); `url` is the apex
 * subpath the shell rewrites to its deployment.
 */
export interface ShellGame {
  /** GameConfig.id — stable identity, also the JSON-LD item id fragment. */
  id: string;
  /** Full title, e.g. 'Tekken 8'. The card heading + JSON-LD name. */
  name: string;
  /** Brand wordmark short form, e.g. 'TEKKEN' / '2XKO'. */
  shortName: string;
  /** URL segment / base path segment (no slashes), e.g. 'tekken'. */
  slug: string;
  /** Apex path the card links to (edge-rewritten to the game deployment). */
  url: string;
  /** The game's own accent hex — the card's only chromatic departure from the
   *  umbrella theme (matches the game's theme.css --color-primary). */
  accent: string;
  /** Bundled key art (public path). The game's own og-default lockup — a
   *  byte-copy of `<game-repo>/public/og-default.png`.
   *
   *  IT CONTAINS ITS OWN COPY LINE, generated by that repo's `scripts/og.ts`
   *  (`KICKER` in SF6's, `L2` in CotW's, inline in 2XKO's and Tekken's), and
   *  those still read "character usage · … · meta over time" — the sentence
   *  `tagline` below was rewritten to stop repeating. The art and the card
   *  therefore disagree today. It is a 20px line inside a 1200px image, so it
   *  renders at ~5px on a card and is effectively illegible, which is why this
   *  was accepted rather than fixed: fixing it means editing five game repos,
   *  regenerating each og-default.png, and re-copying it here — and it changes
   *  every game's social preview as a side effect. If you ever regenerate one,
   *  regenerate all five, and match the new taglines while you are there. */
  art: string;
  /** Self-hosted muted hover-loop (public path), trimmed from the game's own
   *  hero video. Plays over `art` while the selector card is hovered/focused.
   *  OPTIONAL: a game without one simply shows its static key art. */
  video?: string;
  /** The card's blurb: what THIS archive holds that its neighbours' do not.
   *
   *  It used to read "the feature triplet from the game's key art", and copying
   *  the art is exactly how four of five cards ended up as variations on
   *  "Character usage · <something> · meta over time" — a line that describes
   *  every archive here and therefore none of them. Name the thing only this
   *  game's data has: 2XKO's Fuse facet, Tekken's ladder, Tōkon's four-fighter
   *  sides, CotW's patch depth. verify-shell gates distinctness, so a fifth
   *  variation now fails the build rather than shipping.
   *
   *  NEVER A NUMBER THAT GROWS — no roster size, no patch count, no replay
   *  total. Rosters gain DLC and patch trees gain seasons, and this file is
   *  baked into static HTML that only redeploys when the SHELL changes, so a
   *  count here goes stale while nobody is looking. The live number the card
   *  does show comes from the game's own summary.json at runtime.
   *
   *  Wraps to at most TWO lines and never truncates (`.tagline` in index.vue
   *  reserves both). The budget is the narrowest card, which is the sm 2-up at
   *  640 and not the 3-up: ~36 characters a line, so ≤60 characters total. */
  tagline: string;
  /** Absolute /<slug>/sitemap.xml on the apex — referenced by the index. */
  sitemapUrl: string;
  /** Count source for the selector card (PLAN §5 A.4 / Phase 6). SUBPATH-
   *  RELATIVE on purpose: the selector fetches it client-side, so it must go
   *  through the shell's own rewrite (vercel.json) and stay SAME-ORIGIN — an
   *  absolute game-host URL would be cross-origin from the apex and the browser
   *  would block it (the games send no CORS headers). Emitted by each game's
   *  pipeline; a game that hasn't shipped it yet 404s and its count is simply
   *  omitted (never faked, and never derived from the 1 MB replays.json). */
  summaryUrl: string;
}

export const GAMES: ShellGame[] = [
  {
    id: '2xko',
    name: '2XKO',
    shortName: '2XKO',
    slug: '2xko',
    url: '/2xko',
    accent: '#ff2e88',
    art: '/img/games/2xko.png',
    video: '/video/games/2xko.mp4',
    tagline: 'Champion duos, and the Fuse each team ran',
    sitemapUrl: `${SITE_URL}/2xko/sitemap.xml`,
    summaryUrl: '/2xko/data/summary.json',
  },
  {
    id: 'tekken8',
    name: 'Tekken 8',
    shortName: 'TEKKEN',
    slug: 'tekken',
    url: '/tekken',
    accent: '#e13048',
    art: '/img/games/tekken.png',
    video: '/video/games/tekken.mp4',
    tagline: 'Ranked play, up to God of Destruction',
    sitemapUrl: `${SITE_URL}/tekken/sitemap.xml`,
    summaryUrl: '/tekken/data/summary.json',
  },
  {
    // APPEND, don't insert: verify-shell asserts the ItemList JSON-LD
    // positionally, so reordering GAMES silently breaks the gate.
    id: 'sf6',
    name: 'Street Fighter 6',
    shortName: 'SF6',
    slug: 'sf6',
    url: '/sf6',
    // matches the game's theme.css --color-primary; lowercase because the
    // gates compare against lowercased computed values
    accent: '#ff7d00',
    art: '/img/games/sf6.png',
    video: '/video/games/sf6.mp4',
    tagline: 'Any matchup, from either side of it',
    sitemapUrl: `${SITE_URL}/sf6/sitemap.xml`,
    summaryUrl: '/sf6/data/summary.json',
  },
  {
    // Promoted out of UPCOMING on 2026-08-14. Appended, per the note above.
    id: 'tokon',
    // The short form the game is actually called, parallel to 'Tekken 8' and
    // '2XKO'. The full title "MARVEL Tōkon: Fighting Souls" wraps to two lines
    // in the title column, and a wrapped title sits at a different height from
    // its row-mate's, so it lives in the card art and the image alt instead.
    // The measurement behind this MOVED when the "Browse →" CTA left the title's
    // line box: the column is the full card now, 241px at the narrowest regime
    // (the sm 2-up at 640) and 334px at the 3-up, not the 164px it was. The
    // short names all clear that comfortably — verify-shell asserts one line per
    // title at every regime — but the full ones still do not, which is why this
    // field exists.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'MARVEL Tōkon',
    shortName: 'TŌKON',
    slug: 'tokon',
    url: '/tokon',
    // The game's theme.css --color-primary, per the contract above. The
    // coming-soon card carried #00a6ff, sampled from the Marvel CDN wordmark;
    // the shipped skin resolved SOULS blue slightly differently, and it is the
    // computed value that verify-cutover compares through the proxy — so the
    // card follows the game, not the other way round.
    accent: '#03a5fe',
    art: '/img/games/tokon.png',
    video: '/video/games/tokon.mp4',
    tagline: 'Four-fighter teams on a shared life bar',
    sitemapUrl: `${SITE_URL}/tokon/sitemap.xml`,
    summaryUrl: '/tokon/data/summary.json',
  },
  {
    // Game #5, appended per the note above. It never passed through UPCOMING:
    // that array has been empty since Tōkon shipped, so this is a plain append
    // rather than a promotion, and there is no coming-soon card to retire.
    id: 'ffcotw',
    // The short form the game is actually called. The full title
    // "FATAL FURY: City of the Wolves" is longer than any sibling's and wraps
    // in the card's title column; it lives in the card art and the image alt
    // instead, exactly as MARVEL Tōkon's does.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'FATAL FURY: CotW',
    shortName: 'COTW',
    slug: 'ffcotw',
    url: '/ffcotw',
    // The game's theme.css --color-primary. Yellow rather than the sampled
    // FATAL FURY red, by the skin's own collision lever: that red is 11° of hue
    // from Tekken's #e13048 and would be indistinguishable from it at chip size.
    accent: '#ffd21f',
    // A byte-copy of the game repo's own public/og-default.png, which is how
    // 2XKO, Tekken and SF6's cards were made. Tōkon needed a bespoke generator
    // only because it had no game repo at the time; this one does.
    art: '/img/games/ffcotw.png',
    // 1:44–1:55 of the Official Special Anime Trailer, trimmed to the siblings'
    // shape: 1280×720, 30fps, muted (no audio stream at all), 11s.
    video: '/video/games/ffcotw.mp4',
    tagline: 'Every patch since the open beta',
    sitemapUrl: `${SITE_URL}/ffcotw/sitemap.xml`,
    summaryUrl: '/ffcotw/data/summary.json',
  },
  {
    // Game #6, appended per the note above — and the first PROMOTION out of
    // UPCOMING since Tōkon's. Its coming-soon card is retired in this same
    // commit, which is what the `art` swap below is really about: the announced
    // art says "Coming soon to the Replay Database" in 40px type, so leaving it
    // would ship a live, clickable card advertising itself as unavailable.
    id: 'ggst',
    // The short form, parallel to 'MARVEL Tōkon' and 'FATAL FURY: CotW'. The
    // official title is GUILTY GEAR -STRIVE-, and its hyphen-flanked wordmark
    // both wraps in the title column and reads as a stray dash where it breaks.
    // The full spelling survives in the card art, which sets it in the lockup.
    // NOTE: verify-cutover.mjs must use the FULL title in its own table — it
    // asserts against summary.json, which the game emits with the full name.
    name: 'Guilty Gear Strive',
    shortName: 'STRIVE',
    slug: 'ggst',
    url: '/ggst',
    // The game's theme.css --color-primary. UNCHANGED from the coming-soon
    // card's provisional value, which is worth saying out loud because the rule
    // is that the theme wins at flip time and Tōkon's card really did move
    // (#00a6ff → #03a5fe): this skin resolved the gold-foil capsule to the same
    // hex the handoff had anchored, so there was nothing to follow. Its two
    // tight neighbours are unchanged with it — CotW's #ffd21f at Δhue 11 with
    // ΔL .125 against a .12 floor, and the engine's umbrella --color-secondary
    // #fbc318 at Δhue 5 with ΔL .00, separated on chroma alone. Anyone
    // re-sampling this gold has to clear BOTH, not just the live accents.
    accent: '#d9a53a',
    // A byte-copy of the game repo's own public/og-default.png, the way 2XKO,
    // Tekken, SF6 and CotW's were made. This one carries "Character art
    // © ARC SYSTEM WORKS" baked into the image — the Fan Kit licence's
    // Article 3.1 attribution travelling with the art onto the front door. It
    // is the only card art here with a licence obligation attached, so it may
    // be re-exported from that repo but never cropped past the notice.
    // It inherits the copy-line disagreement described on `art` above: the
    // lockup reads "Character usage · matchups · meta over time" while the
    // tagline says something else entirely. Accepted on the same terms as the
    // other five — ~5px on a rendered card — not overlooked.
    art: '/img/games/ggst.png',
    // NO hover loop, deliberately: CotW shipped its own flip without one and
    // gained it in a later commit, and the field is optional precisely so a
    // launch is not gated on trimming a trailer. This card shows static art.
    // The archive's own shape is the line worth having here, and no sibling can
    // claim it: the eight channels upload whole SETS (every one's median run
    // is over three and a half minutes, against a ~3-minute Strive game), while
    // the Replay Theater catalogue contributes single matches cut out of
    // tournament VODs at an offset. Not a count, and it cannot go stale.
    tagline: 'Whole sets, and matches cut from tournament streams',
    sitemapUrl: `${SITE_URL}/ggst/sitemap.xml`,
    summaryUrl: '/ggst/data/summary.json',
  },
];

/**
 * Games ANNOUNCED but not yet in the archive — the selector's coming-soon cards
 * and nothing else.
 *
 * Deliberately a SEPARATE array with its own narrower type rather than a
 * `status` field on ShellGame. GAMES feeds three surfaces — the cards, the
 * ItemList JSON-LD, and the sitemap index — and only the first of those may show
 * a game that has no replays: an upcoming game in structured data or a sitemap is
 * a lie to crawlers. A `status` flag would push that correctness burden onto
 * every consumer forever, and two of the three fail SILENTLY when someone
 * forgets. This type has no `url`, no `sitemapUrl` and no `summaryUrl` at all, so
 * `modules/sitemap-index.ts` and the JSON-LD literally cannot reach it, even by
 * mistake. Only the card grid reads UPCOMING.
 *
 * Promoting one when its pipeline ships: move the entry into GAMES (appending,
 * per the note there), fill in the URL fields, and add the vercel.json rewrite
 * pair + the insights rewrite in the same commit — see README "Adding a game to
 * the selector".
 */
export interface UpcomingGame {
  /** Stable identity — the v-for key, and the future GameConfig.id. */
  id: string;
  /** The SHORT display form — the card's title column and nothing else. NOT the
   *  full title: spelled out, every one of these wraps, and a wrapped title sits
   *  at a different height from its row-mate's. The column is the full card
   *  width since the CTA moved onto the count row — 241px at the narrowest
   *  regime (sm 2-up at 640), 334px at the 3-up — and the full titles still
   *  exceed it. Parallel to the live cards' 'Tekken 8' / 'MARVEL Tōkon' /
   *  'FATAL FURY: CotW'. verify-shell gates one line per title at every
   *  regime. */
  name: string;
  /** The full title as the rights holder writes it, diacritics included. The
   *  card title cannot carry it (see `name`), so the image ALT and the card art
   *  do. A hard-coded literal here is what shipped the Tōkon alt onto every
   *  card that followed; index.vue binds this instead. */
  fullName: string;
  /** Brand wordmark short form. Official casing/diacritics render verbatim,
   *  same principle as Tekken's deliberate 'TEKKEN'. */
  shortName: string;
  /** The slug this game WILL own once it ships. ASCII — the macron is display
   *  only and never reaches a URL. */
  slug: string;
  /** Accent hex, lowercase (the gates compare against lowercased computed
   *  values). Drives the accent bar and the Coming Soon badge. */
  accent: string;
  /** Bundled card art (public path), 1200×630 to match the live cards. */
  art: string;
  /** Blurb describing the GAME, not an archive — there is no archive yet, and
   *  claiming one would be the same lie this type's missing url/summaryUrl
   *  fields exist to prevent. Same shape as ShellGame.tagline otherwise: two
   *  lines, ≤60 characters, distinct from every sibling (gated).
   *  NEVER A DATE — see below. */
  tagline: string;
}

// Empty from 2026-08-14 (MARVEL Tōkon's promotion into GAMES) until three games
// were announced; two, since Guilty Gear Strive was promoted into GAMES on
// 2026-09-09. The narrow type above is what kept that window honest, and it is
// what keeps the remaining two out of the sitemap index and the ItemList now.
//
// PROMOTING ONE IS A SUBTRACTION HERE AND AN APPEND THERE, in the same commit.
// Strive's entry did not move between the arrays: UpcomingGame and ShellGame
// share only five of their fields, so `fullName` was DROPPED (ShellGame has no
// such field) and `url`, `sitemapUrl` and `summaryUrl` were added. The full
// title therefore leaves the DOM at promotion — it lives in the card art and
// nowhere else, exactly as MARVEL Tōkon's and FATAL FURY's do.
//
// ORDER IS DISPLAY ORDER. Unlike GAMES — where APPEND-don't-insert protects a
// POSITIONAL JSON-LD gate — this array reaches only the card grid, which renders
// it in sequence. verify-shell asserts the three cards positionally too, so
// reordering here is a deliberate act with a failing gate attached, not a silent
// one.
//
// ACCENTS ARE PROVISIONAL, and say so per entry. Each is the modal exact fill of
// an official asset (the sampling method is in scripts/card-art-upcoming.mjs),
// lifted where the sampled value is too dark to carry the badge's 11px text.
// At flip time THE THEME WINS: Tōkon's card carried #00a6ff and the shipped skin
// resolved to #03a5fe, and the card followed the game rather than the reverse.
//
// The separation rule every one of them clears, against all SIX live accents
// (Strive's gold joined that set when it was promoted), the umbrella teal, and
// each other: OKLCH Δhue ≥ 25, or Δhue ≥ 10 with |ΔL| ≥ .12. It is the rule the
// game skins already use, and it is why FATAL FURY demoted its own sampled red
// (11° from Tekken) to secondary.
export const UPCOMING: UpcomingGame[] = [
  {
    id: 'avatar',
    // Avatar Legends: The Fighting Game. The studio credits are the one fact
    // here that no single official surface settles, so the disagreement is
    // recorded rather than smoothed over:
    //   · Steam app 2424420 (publisher-submitted fields) — developer
    //     "Gameplay Group International", publishers "PM Studios, Inc." and
    //     "Paramount Games"
    //   · nintendo.com product page — publisher "PM Studios", no developer
    //   · paramountgames.com/games/avatar-legends-the-fighting-game — credits
    //     "Paramount Games Studio" as both
    // Resolved by the maintainer's own confirmation: developer Gameplay Group
    // International, publisher PM Studios, Inc. The tagline carries the
    // rights-holder × developer pair; "Paramount" is the rights holder, as
    // "Marvel" was on Tōkon's card before that one moved to describing its
    // archive. This is the only card left in the ×-credit shape, which is why
    // it is the one that kept its line unchanged.
    // Slug is 'avatar', not ComboForge's 'ava': this becomes a permanent public
    // path and readability wins there; the CF id stays a config map.
    name: 'Avatar Legends',
    fullName: 'Avatar Legends: The Fighting Game',
    shortName: 'AVATAR',
    slug: 'avatar',
    // PROVISIONAL. Sampled from the official site's own logo
    // (avatarfighters.com): a dusk indigo #363c88, 54.3% of that asset's flat
    // fills. Lifted L .395 → .778 for AA — the sampled value is 2.06:1 on the
    // card ground and the badge sets 11px text in it.
    // WORTH KNOWING before re-sampling: the logo at
    // paramountgames.com/avatar-assets/brand/avatar-logo-clean.png and all four
    // element seals under /avatar-assets/brand/seals/ are pure WHITE line art
    // on transparent — zero chroma, no accent to take. The key art is a painted
    // composition whose dominant fills are a cream wash and a fire red 11° from
    // Tekken. The indigo is the only viable band the official art offers.
    // Δhue 36 from Tōkon, 90 from the umbrella teal. See the gbvsr entry for
    // why these two are separated by lightness.
    accent: '#aeacff',
    art: '/img/games/avatar.png',
    tagline: 'Four elements · Paramount × Gameplay Group',
  },
  {
    id: 'gbvsr',
    // Granblue Fantasy Versus: Rising — "© Cygames, Inc. Developed by ARC
    // SYSTEM WORKS", verbatim from the footer of the official site
    // rising.granbluefantasy.jp/en/about. That single line is both credits, and
    // the tagline carried both until the 2026-09-06 copy pass. It names CYGAMES
    // ONLY: ASW closed the Strive line two entries up as well, and a reader
    // scanning eight cards met the same four words twice. Cygames is the rights
    // holder, which is the half that identifies the game.
    // THE REASON HAS SINCE EXPIRED AND THE LINE IS KEPT ANYWAY. Strive was
    // promoted into GAMES on 2026-09-09 and a live card's tagline describes its
    // ARCHIVE, not its studio, so no card names ASW now and the duplication
    // this line was shortened to avoid cannot recur. Restoring the developer
    // credit here would be a copy change made for a reason that no longer
    // holds; naming the rights holder was the better line on its own merits.
    name: 'Granblue Rising',
    fullName: 'Granblue Fantasy Versus: Rising',
    shortName: 'GBVSR',
    slug: 'gbvsr',
    // PROVISIONAL. Sampled from the official key-visual logo
    // (rising.granbluefantasy.jp/assets/images/kv_logo.9880ca03.png): the
    // ultramarine #0000c8 is 72.5% of its flat fills. Lifted L .376 → .593 for
    // AA (the sampled value is 1.75:1) and carried +8° of hue, which is what
    // buys Δhue 28 from Tōkon's #03a5fe. At the sampled hue it could only clear
    // Tōkon on lightness, and every lightness dark enough to do that fails AA —
    // the same squeeze Strive's red hit, resolved the other way because this
    // hue had somewhere to go and that one did not.
    // The logo's sky #5bc9fa was the obvious alternative and is blocked
    // outright: Δhue 14 from Tōkon with ΔL .096, under both floors. It survives
    // as the card art's second hue instead.
    // SIBLINGS, DELIBERATELY: this and Avatar are the only two cards the
    // official art puts in the same band (Δhue 12), and at 2-up they share the
    // last grid row. They are separated by lightness — ΔL .185, half again the
    // floor — a deep royal blue beside a pale periwinkle. Anyone re-sampling
    // either one has to re-check the pair, not just the live five.
    accent: '#5569ff',
    art: '/img/games/gbvsr.png',
    tagline: "Cygames' Granblue cast, one on one",
  },
];
